### ISSUE TITLE
Problem with the node sensorTag on Node-RED

### ISSUE THREAD

**Issue by alphabeat** [sandeepmistry/node-sensortag#15]
Hello, 

First of all, thank you for providing such tools as noble and the sensortag library, that helped ma a lot !

I have a problem with the SensorTag and I have no idea of where it is coming from, despite a lot of debugging... I have two SensorTags and face the same problem with both of them :
the SensorTags disconnect randomly with no reason and the only way to reconnect them is to press the Publish button on Node-RED (which means I have to make a change on my sheet and undo that change). I only have a SensorTag node and a debug node on the sheet. I run node-RED on a raspberry Pi (raspbian wheezy) and use a USB Bluetooth 4.0 dongle.

Sometimes the deconnexion happens after 5 minutes, sometimes it's after 30... 

I have a few ideas to solve this problem but I'm not sure they are relevant and/or doable : 
- reload the node completely when the 'disconnect' event is triggered but then, how to differenciate a 'normal' disconnexion when the node is deleted from the sheet and an undesired disconnexion ? And I'm not even sure that a node is reloadable...
- reconnect the sensorTag when the connexion drops (but again, we can't distinguish the two phenomenons). I tried to install the Lahorde version with the reconnexion feature, but that didn't change anything. 

Do you have an idea of where the problem might be coming from ? Is it the node itself ? the sensortag library ? the noble library ? 

I'm a bit lost and I don't have a lot of experience in node.js or debugging so I don't really know how to deal with that issue. 

Another question : is it possible to connect two SensorTags at the same time with Node-RED ?

I also noticed that when I delete a SensorTag node from my sheet and add a new one, the old one is still active (I get every data twice !). I managed to fix that by removing the 'connect' and 'disconnect' listeners when the event 'disconnect' is triggered. 

Thank you in advance for your answers,
Julien K.

**Comment by vielmetti** [comment]
Reopening....

The "random sensortag disconnect" feature is part of the stock sensortag firmware, which will go to sleep to save battery.

This organization has built new firmware for the sensortag that disables sleep mode, so that the device will be on continuously. They don't release source code for it but the object might be useful to your purpose. From all I can tell this doesn't otherwise affect communications with the device.

http://www.myweathercenter.net/installing-a-new-firmware-for-ti-sensortag/

**Comment by Lahorde** [comment]
@alphabeat I've modified test.js in order to continue test execution after a reconnection. 
@vielmetti check out http://stackoverflow.com/questions/22090954/how-to-modify-the-ti-sensortag-firmware-to-advertise-indefinitely , to reduce power consumption you can modify 
     #define DEFAULT_ADVERTISING_INTERVAL          16384
"For a Central to be able to connect to a Peripheral, the Peripheral must be advertising. It sends advertising packets with a time interval, known as the advertising interval, that ranges between 20 ms and 10.24 s. The advertising interval affects how long it takes to initiate a connection."

With this modification and https://github.com/Lahorde/node-sensortag sensortag won't be disconnected anymore.

**Comment by vielmetti** [comment]
@alphabeat You write 

> I added a button on the left of the node SensorTag (just like the node Inject) 

Can you share that patch? It would be useful.

Thanks @Lahorde for the changes. I notice that your version of node-sensortag also supports reading the battery level, that's helpful too.

**Comment by vargascyntiam** [comment]
I am new to node red and was trying to use this library.  I downloaded it from here,  because it is different than the one npm gives me.  However, when I run node, it says that it is waiting to register sensortag.  Before I used thethingbox-sensortag, but I already uninstalled it so it wouldn't generate any conflict.

**Comment by sandeepmistry** [comment]
@vargascyntiam the version of ``node-sensortag`` that in ``master`` is not compatible with the ``node-red`` as far as I know.

@vielmetti has created an issue here to update ``node-red-nodes`` support: https://github.com/node-red/node-red-nodes/issues/107

**Comment by vielmetti** [comment]
Yes, there is an open issue. I've now got both a Mac and a Pi ready to test this, and a couple of sensortags (both v1 and v2, and three different firmware versions of the v1). I'll update issues when there's any progress.
