### ISSUE TITLE
Raspbian boot

### ISSUE THREAD

**Issue by joseLourenco** [sandeepmistry/node-sensortag#71]
Hi,

How can I put my node.js app, with node_sensortag, running after the boot?

Thanks

**Comment by danielbh** [comment]
I had problems with this yestarday. I tried to do it in the init.d file but supervisor causes huge memory usage issues when run there.  You might be able to do an init.d set up more easily in your project. For now we had to hack it with crontab. Would love to figure out the proper way. Additionally we had to delay it to run to work. I believe it's because Bluetooth isn't activated when crontab reboots are done initially. This is how we did it.

sudo crontab -e

@reboot sleep 10 && cd /project-directory && /path-to-node/node app.js > app.logs

Let me know if that works. Again it's a temporary hack until we figure out the proper way.

On 24 Mar 2016, at 02:25, joseLourenco <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

How can I put my node.js app, with node_sensortag, running after the boot?

Thanks

�

**Comment by joseLourenco** [comment]
Hi,

First of all, thanks for your reply.

This "@reboot sleep 10 && cd /project-directory && sudo /path-to-node/node app.js > app.logs" is a command line right?

My project directory is /home/pi/poRsCHE.
But the "path-to-node" what is it? Is like "usr/bin/node"? How do I know the right address?

**Comment by danielbh** [comment]
No you put the @reboot in the crontab config file.
'which node' to find the path

Again I want to re-emphasize this is a hack imo and to try to do it in the init.d directory instead of crontab. See above links for more info.

Also if anyone watching this repo wants to work with me to develop a better solution I'm all ears.

On Mar 24, 2016, at 11:25 AM, joseLourenco <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

First of all, thanks for your reply.

This "@reboot<https://github.com/reboot> sleep 10 && cd /project-directory && sudo /path-to-node/node app.js > app.logs" is a command line right?

My project directory is /home/pi/poRsCHE.
But the "path-to-node" what is it? Is like "usr/bin/node"? How do I know the right address?

�

**Comment by joseLourenco** [comment]
Ok, thanks.

I'm going to test and I'll report you.

**Comment by joseLourenco** [comment]
It worked and it didn't work...

In my app I have a bleno service to receive data from my Android app and I have node-sensortag to receive data from the SensorTag. 
After I boot the Raspberry, it advertises the bleno service but after it receives the data from the Android app, it doesn't connect with the SensorTag.

Do you have som explanation for this? :S

**Comment by danielbh** [comment]
I have no idea. We only use this module for bluetooth communication to the sensortag.  We have no communication directly to mobile devices with bluetooth.

**Comment by danielbh** [comment]
Sorry I can't help. We will eventually implement bluetooth to mobile devices, but not at this time.

**Comment by joseLourenco** [comment]
The bleno modules was developed by the same author of the node-sensortag, Sandeep Mistry.

My app works well when I execute it by command line. It's just not working well by boot (by your guide).

I'll try other guides. 
Meanwhile if you have some new idea, I'm here.

Thanks for your support.

**Comment by danielbh** [comment]
Yeah there is something going on behind the scenes on boot up. I'd be very interested to know a way to make this solution portable.

Sent from my iPhone

On 24 Mar 2016, at 13:45, joseLourenco <notifications@github.com<mailto:notifications@github.com>> wrote:


The bleno modules was developed by the same author of the node-sensortag, Sandeep Mistry.

My app works well when I execute it by command line. It's just not working well by boot (by your guide).

I'll try other guides.
Meanwhile if you have some new idea, I'm here.

Thanks for your support.

�

**Comment by joseLourenco** [comment]
Hi

I have success with the crontab file but with a line of code a bit different:
@reboot sleep 10 && su pi -c 'sudo node-path/node /home/pi/appDirectory/app.js < /dev/null &'

I hope it will help you.

Best regards

**Comment by danielbh** [comment]
The last part from what I sent your writes to a log file. Not sure what your code is doing.

Sent from my iPhone

On 25 Mar 2016, at 12:57, joseLourenco <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

I have success with the crontab file but with a line of code a bit different:
@reboot<https://github.com/reboot> sleep 10 && su pi -c 'sudo node-path/node /home/pi/appDirectory/app.js < /dev/null &'

I hope it will help you.

Best regards

�

**Comment by joseLourenco** [comment]
the problems was not you line of code with logs.

was my js app that had a process.stdout that was killing the connection with the sensortag.

**Comment by sandeepmistry** [comment]
@joseLourenco I'm closing this now, as it looks like you question is solved.

In the future, please only create issues for node-sensortag related items, there are much better places to ask general questions related to Linux and Node.js.


@danielbh thank you for helping out!
